eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8801/eureka/
server:
  port: 8803
spring:
  application:
    name: userconsumer
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  redis:  #redis配置
    database: 1
    host: 127.0.0.1
    port: 6379
    timeout: 300
#    pool:
#      max-active: 8
#      min-idle: 0